version: '2'
services:
    registry:
        image: registry
        ports:
            - "127.0.0.1:5000:5000"
        volumes:
            - ./data:/var/lib/registry
        environment:
            - REGISTRY_STORAGE_DELETE_ENABLED=true
